# Generated by Django 2.2 on 2021-05-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('realname', models.CharField(max_length=254, null=True)),
                ('password', models.CharField(max_length=18)),
                ('telephone', models.CharField(max_length=11, null=True)),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], default=3)),
                ('age', models.IntegerField(null=True)),
                ('education', models.IntegerField(choices=[(1, '博士'), (2, '研究生'), (3, '本科'), (4, '高中'), (5, '高中及一下')], null=True)),
                ('signature', models.TextField(null=True)),
                ('avatar', models.CharField(max_length=254, null=True)),
                ('role', models.IntegerField(choices=[(1, '员工'), (2, '用户')])),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('desc', models.TextField()),
                ('img', models.CharField(max_length=254, null=True)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.IntegerField(choices=[(1, '发布招聘'), (2, '求职')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.User')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='front.Jobtype')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.User')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.Offer')),
                ('origin_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Comments')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=254, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.User')),
            ],
        ),
    ]
